---
abstract: 'Perl extension for getting symbols lists                          from web resources'
author:
  - 'Josef Ezra <jezra@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Finance-TickerSymbols
no_index:
  directory:
    - t
    - inc
requires:
  LWP: '6'
  LWP::Protocol::https: '6'
version: '3.11'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
